services:
    backend:
        build: ./Backend
        networks:
        - app-network
        depends_on:
        - database

    database:
        build: ./Database
        environment: 
          POSTGRES_USER: usr
          POSTGRES_DB: db
          POSTGRES_PASSWORD: pwd
        networks:
        - app-network
        volumes:
        - db-data:/var/lib/postgresql/data

    httpd:
        build: ./HTTP_server
        ports:
        - "80:80"
        networks:
        - app-network
        depends_on:
        - backend

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 
    driver: local